apiVersion: '2018-10-01'
location: eastus
name: mycontainernew
properties:
  containers:
  - name: dotnetappnew
    properties:
      image: demoregistry3000.azurecr.io/dotnetapp
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      volumeMounts:
      - mountPath: /mounts/secrets
        name: volumesecret
  osType: Linux
  imageRegistryCredentials:
    - server: demoregistry3000.azurecr.io
      username: demoregistry3000
      password: <password>
  volumes:
  - name: volumesecret
    secret:
      storage-connection: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWRlbW9zdG9yZTQwMDAwO0FjY291bnRLZXk9b0tTVXNtKzVIc3lJVnhPUlFBWm9XcVl2eE9WUjgxRjNaQ293ck5lL2dVdlZsNDA5cThFMlRNUXRabHljdU45ZkkvT3hWQnUvcUtEaE5OU1FkMDlMWnc9PTtFbmRwb2ludFN1ZmZpeD1jb3JlLndpbmRvd3MubmV0
tags: null
type: Microsoft.ContainerInstance/containerGroups